app:
  version: 0.0.1-SNAPSHOT
  enableCheckDigitConversion: ${CHECK_DIGIT_CONVERSION:false}

fhir:
  extensions:
    fernMetaExt: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Extension-Fernmetastasen"
    opIntention: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Extension-OPIntention"
    stellungOP: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Extension-StellungZurOp"
    systIntention: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Extension-SYSTIntention"
    sysTheraProto: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Extension-SystemischeTherapieProtokoll"
    dataAbsentReason: "http://hl7.org/fhir/StructureDefinition/data-absent-reason"
    genderAmtlich: "http://fhir.de/StructureDefinition/gender-amtlich-de"
  systems:
    patientId: "https://fhir.diz.uk-erlangen.de/identifiers/patient-id"
    identifierType: "http://terminology.hl7.org/CodeSystem/v2-0203"
    conditionId: "https://fhir.diz.uk-erlangen.de/identifiers/onkostar-xml-condition-id"
    observationId: "https://fhir.diz.uk-erlangen.de/identifiers/onkostar-xml-observation-id"
    procedureId: "https://fhir.diz.uk-erlangen.de/identifiers/onkostar-xml-procedure-id"
    medicationStatementId: "https://fhir.diz.uk-erlangen.de/identifiers/onkostar-xml-medication-statement-id"
    observationCategorySystem: "http://terminology.hl7.org/CodeSystem/observation-category"
    loinc: "http://loinc.org"
    idco3Morphologie: "urn:oid:2.16.840.1.113883.6.43.1"
    gradingDktk: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/GradingCS"
    uicc: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/UiccstadiumCS"
    tnmPraefix: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/TNMcpuPraefixTCS"
    tnmTCs: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/TNMTCS"
    tnmNCs: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/TNMNCS"
    tnmMCs: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/TNMMCS"
    tnmYSymbolCs: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/TNMySymbolCS"
    tnmRSymbolCs: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/TNMrSymbolCS"
    tnmMSymbolCs: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/TNMmSymbolCS"
    fMLokalisationCS: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/FMLokalisationCS"
    jnuCs: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/JNUCS"
    icd10gm: "http://fhir.de/CodeSystem/bfarm/icd-10-gm"
    adtSeitenlokalisation: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/SeitenlokalisationCS"
    snomed: "http://snomed.info/sct"
    opIntention: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/OPIntentionCS"
    systTherapieart: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/SYSTTherapieartCS"
    ops: "http://fhir.de/CodeSystem/bfarm/ops"
    lokalBeurtResidualCS: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/LokaleBeurteilungResidualstatusCS"
    gesamtBeurtResidualCS: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/GesamtbeurteilungResidualstatusCS"
    systIntention: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/SYSTIntentionCS"
    systStellungOP: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/SYSTStellungOPCS"
    ctcaeGrading: "http://hl7.org/fhir/us/ctcae/CodeSystem/ctcae-grade-code-system"
    sideEffectTypeOid: "urn:oid:1.2.276.0.76.3.1.131.1.5.20"
    opComplication: "urn:oid:1.2.276.0.76.3.1.131.1.5.122"
    observationValue: "http://terminology.hl7.org/CodeSystem/v3-ObservationValue"
    genderAmtlichDe: "http://fhir.de/CodeSystem/gender-amtlich-de"
  profiles:
    histologie: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Observation-Histologie"
    grading: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Observation-Grading"
    tnmC: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Observation-TNMc"
    tnmP: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Observation-TNMp"
    fernMeta: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Observation-Fernmetastasen"
    condition: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Condition-Primaerdiagnose"
    genVariante: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Observation-GenetischeVariante"
    opProcedure: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Procedure-Operation"
    stProcedure: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Procedure-Strahlentherapie"
    systMedStatement: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-MedicationStatement-Systemtherapie"
    miiPatientPseudonymisiert: "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/PatientPseudonymisiert"
    deathObservation: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Observation-TodUrsache"
  display:
    histologyLoinc: "Histology and Behavior ICD-O-3 Cancer"
    gradingLoinc: "Grade pathology value Cancer"
    tnmcLoinc: "Stage group.clinical Cancer"
    tnmpLoinc: "Stage group.pathology Cancer"
    fernMetaLoinc: "Distant metastases.clinical"
    deathLoinc: "Primary cause of death"
  url:
    tnmPraefix: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Extension-TNMcpuPraefix"
spring:
  profiles:
    active: ${ACTIVE_PROFILE:default}
  application:
    name: onkoadt-to-fhir
  cloud:
    function:
      definition: getMeldungExportOnkoProcessor
    stream:
      bindings:
        getMeldungExportOnkoProcessor-in-0:
          destination: onkostar.MELDUNG_EXPORT${YEAR_LIMITATION_SUFFIX:}
        getMeldungExportOnkoProcessor-in-1:
          destination: fhir.onkoadt.Observation${YEAR_LIMITATION_SUFFIX:}
        getMeldungExportOnkoProcessor-out-0:
          destination: fhir.onkoadt.MedicationStatement${YEAR_LIMITATION_SUFFIX:}
          producer:
            partition-count: ${FHIR_OUTPUT_TOPIC_PARTITION_COUNT:12}
        getMeldungExportOnkoProcessor-out-1:
          destination: fhir.onkoadt.Observation${YEAR_LIMITATION_SUFFIX:}
          producer:
            partition-count: ${FHIR_OUTPUT_TOPIC_PARTITION_COUNT:12}
        getMeldungExportOnkoProcessor-out-2:
          destination: fhir.onkoadt.Procedure${YEAR_LIMITATION_SUFFIX:}
          producer:
            partition-count: ${FHIR_OUTPUT_TOPIC_PARTITION_COUNT:12}
        getMeldungExportOnkoProcessor-out-3:
          destination: fhir.onkoadt.Condition${YEAR_LIMITATION_SUFFIX:}
          producer:
            partition-count: ${FHIR_OUTPUT_TOPIC_PARTITION_COUNT:12}
        getMeldungExportOnkoProcessor-out-4:
          destination: fhir.onkoadt.Patient${YEAR_LIMITATION_SUFFIX:}
          producer:
            partition-count: ${FHIR_OUTPUT_TOPIC_PARTITION_COUNT:12}

      kafka:
        streams:
          binder:
            configuration:
              cache.max.bytes.buffering: 0
              max.request.size: ${MAX_REQUEST_SIZE:20971520}
              num.stream.threads: ${NUM_STREAM_THREADS:1}
              default:
                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          bindings:
            getMeldungExportOnkoProcessor-in-0:
              consumer:
                application-id: onko-meldung-exp-grouped-processor${YEAR_LIMITATION_SUFFIX:}
            getMeldungExportOnkoProcessor-in-1:
              consumer:
                valueSerde: org.miracum.kafka.serializers.KafkaFhirSerde
                application-id: onko-meldung-exp-condition-processor${YEAR_LIMITATION_SUFFIX:}
            getMeldungExportOnkoProcessor-out-0:
              producer:
                valueSerde: org.miracum.kafka.serializers.KafkaFhirSerde
                configuration:
                  compression.type: ${COMPRESSION_TYPE:gzip}
            getMeldungExportOnkoProcessor-out-1:
              producer:
                valueSerde: org.miracum.kafka.serializers.KafkaFhirSerde
                configuration:
                  compression.type: ${COMPRESSION_TYPE:gzip}
            getMeldungExportOnkoProcessor-out-2:
              producer:
                valueSerde: org.miracum.kafka.serializers.KafkaFhirSerde
                configuration:
                  compression.type: ${COMPRESSION_TYPE:gzip}
            getMeldungExportOnkoProcessor-out-3:
              producer:
                valueSerde: org.miracum.kafka.serializers.KafkaFhirSerde
                configuration:
                  compression.type: ${COMPRESSION_TYPE:gzip}
            getMeldungExportOnkoProcessor-out-4:
              producer:
                valueSerde: org.miracum.kafka.serializers.KafkaFhirSerde
                configuration:
                  compression.type: ${COMPRESSION_TYPE:gzip}

  kafka:
    bootstrapServers: ${BOOTSTRAP_SERVERS:localhost:9092}
    security.protocol: ${SECURITY_PROTOCOL:PLAINTEXT}
    ssl:
      trust-store-type: PKCS12
      trust-store-location: file://${SSL_TRUST_STORE:/opt/kafka-certs/ca.p12}
      trust-store-password: ${SSL_TRUST_STORE_PASSWORD}
      key-store-type: PKCS12
      key-store-location: file://${SSL_KEY_STORE_FILE:/opt/kafka-certs/user.p12}
      key-store-password: ${SSL_KEY_STORE_PASSWORD}
    producer:
      compression-type: gzip
